
--SQL DOCUMENT https://www.w3schools.com/sql/sql_foreignkey.asp

-- USE [master]; DROP DATABASE [SocialMediaDB];
-- CREATE DATABASE [SocialMediaDB];

USE [SocialMediaDB];

--DROP CONSTRAINTS 'F'=FORREIGN KEY
IF OBJECT_ID('FK_PostUser','F') IS NOT NULL ALTER TABLE [Posts] DROP CONSTRAINT FK_PostUser;
IF OBJECT_ID('FK_CommentPost','F') IS NOT NULL ALTER TABLE [Comments] DROP CONSTRAINT FK_CommentPost;
IF OBJECT_ID('FK_CommentUser','F') IS NOT NULL ALTER TABLE [Comments] DROP CONSTRAINT FK_CommentUser;

--DROP TABLE  'U'= TABLE
IF OBJECT_ID('Users','U') IS NOT NULL DROP TABLE [Users];
IF OBJECT_ID('Posts','U') IS NOT NULL DROP TABLE [Posts];
IF OBJECT_ID('Comments','U') IS NOT NULL DROP TABLE [Comments];


CREATE TABLE [Users]
(
	[UserID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	,[Firsname] VARCHAR(50) NOT NULL
	,[Lastname] VARCHAR(50) NOT NULL
	,[Email] VARCHAR(30) NOT NULL
	,[Datebirth] DATETIME NOT NULL
	,[Phone] VARCHAR(10)
	,[Active] BIT NOT NULL
);

CREATE TABLE [Posts]
(
	[PostID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	,[UserID] INT NOT NULL
	,[Date] DATETIME NOT NULL
	,[Description] VARCHAR(1000) NOT NULL
	,[Image] VARCHAR(500)  
);


CREATE TABLE [Comments]
(
	[CommentId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	,[PostID] INT NOT NULL
	,[UserID] INT NOT NULL
	,[Description] VARCHAR(500) NOT NULL
	,[Date] DATETIME NOT NULL
	,[Active] BIT NOT NULL
);

--CONSTRAINTS
ALTER TABLE [Posts]  ADD CONSTRAINT FK_PostUser FOREIGN KEY (UserID) REFERENCES [Users](UserID);
ALTER TABLE [Comments] ADD CONSTRAINT FK_CommentPost FOREIGN KEY (PostID) REFERENCES [Posts](PostID)
ALTER TABLE [Comments] ADD CONSTRAINT FK_CommentUser FOREIGN KEY (UserID) REFERENCES [Users](UserID);